# .gitlab-ci.yml

image: "python:3.6"

stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true

job 1:
  stage: build
  script: echo "Build Nieh"
job 2:
  stage: test
  script: echo "Test Nieh"

job 3:
  stage: deploy
  script: echo "Deploy nieh"
