# .gitlab-ci.yml

image: "python:3.6"

stages:
  - test
  - build
  - staging
  - production

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/dertajora1/django-blog:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/dertajora1/django-blog:latest

Test 1:
  stage: test
  script: 
    # - pip install -r requirements.txt
    - echo "Test Model Nieh"
    - python manage.py test test/
Dummy Test 2:
  stage: test
  script: echo "Test View Nieh"
Dummy Test 3:
  stage: test
  script: echo "Last Final Test"


Build:
  stage: build
  script: 
    - echo "Build Nieh"
    - pip install -r requirements.txt
Deploy Staging:
  stage: staging
  script: echo "Deploy staging nieh"
  only:
    - master
Deploy Production:
  stage: production
  script: echo "Deploy prod nieh"
  when: manual
  only:
    - master
