# .gitlab-ci.yml

image: "python:3.6"

stages:
  - build
  - test
  - staging
  - production

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true

Test Build:
  stage: build
  script: 
    - echo "Build Nieh"
    - pip install -r requirements.txt
Test 1:
  stage: test
  script: 
    - echo "Test Model Nieh"
    - python manage.py test test/
Dummy Test 2:
  stage: test
  script: echo "Test View Nieh"
Dummy Test 3:
  stage: test
  script: echo "Last Final Test"
Deploy Staging:
  stage: staging
  script: echo "Deploy staging nieh"
Deploy Production:
  stage: production
  script: echo "Deploy prod nieh"
  when: manual
