# .gitlab-ci.yml

image: "python:3.6"

stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true

Test Build:
  stage: build
  script: echo "Build Nieh"
Test Model:
  stage: test
  script: echo "Test Model Nieh"
Test View:
  stage: test
  script: echo "Test View Nieh"
Last View:
  stage: test
  script: echo "Last Final Test"
Test Deploy:
  stage: deploy
  script: echo "Deploy nieh"
