version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8005:8001"
    depends_on:
      - db
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "10"
