version: '3'

services:
  db:
    image: postgres
  web:
    image: dertajora/django-blog
    command: python3 manage.py runserver 0.0.0.0:8001
    ports:
      - "8006:8001"
    restart: always
    logging:
      options:
        max-size: "500k"
        max-file: "10"
